branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: refactor
          release: patch
        - type: revert
          release: patch
        - type: build
          scope: "{mvn,docker,helm}"
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
          - type: fix
            section: "Bug Fixes"
          - type: refactor
            section: "Refactors"
          - type: revert
            section: "Reverts"
          - type: build
            section: "Build"
          - type: test
            section: "Tests"
          - type: docs
            section: "Documentation"
          - type: deploy
            section: "Deployment"
          - type: ci
            section: "CI"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/exec"
    - prepareCmd: "mvn -B versions:set -DnewVersion=${nextRelease.version} -DgenerateBackupPoms=false && sed -i \"s|image: migas77/exchange-rate-api:.*|image: migas77/exchange-rate-api:v${nextRelease.version}|\" docker-compose.yml && mvn -B clean verify -Dci -Dgenerate-openapi -DskipTests"
  - - "@semantic-release/git"
    - assets:
        - "docker-compose.yml"
        - "pom.xml"
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - assets:
      - path: "target/*.jar"
        label: "Application JAR"
      - path: "target/openapi.json"
        label: "OpenAPI Specification JSON"
      - path: "target/openapi.yaml"
        label: "OpenAPI Specification YAML"
