spring.application.name=exchange-rate-api
spring.application.version=@project.version@
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
# only run security filters for request dispatcher type (only when first enters the gateway)
spring.security.filter.dispatcher-types=request
spring.mvc.problemdetails.enabled=true
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
springdoc.swagger-ui.config-url=/gw/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/gw/v3/api-docs
springdoc.swagger-ui.oauth2-redirect-url=/gw/swagger-ui/oauth2-redirect.html
app.jwt.jwt-signing-key=${APP_JWT_JWT_SIGNING_KEY}
app.jwt.access-exp-time=${APP_JWT_ACCESS_EXP_TIME}
app.jwt.refresh-exp-time=${APP_JWT_REFRESH_EXP_TIME}
app.rate-limit.capacity=10
app.rate-limit.period=1m
app.rate-limit.timeout=500ms
app.clients.exchange-rates.base-url=${EXCHANGE_RATE_API_BASE_URL}
app.clients.exchange-rates.access-key=${EXCHANGE_RATE_API_ACCESS_KEY}
app.clients.exchange-rates.connect-timeout=3s
app.clients.exchange-rates.read-timeout=8s
app.clients.exchange-rates.caching-ttl=1m
logging.structured.format.console=ecs
logging.structured.json.customizer=com.miguelbf.exchangerateapi.config.logging.CustomLoggingJsonMembersCustomizer
