spring.application.name=exchange-rate-api
spring.application.version=@project.version@
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.username=ci
spring.datasource.password=ci
spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=create
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
app.jwt.access-exp-time=10
app.jwt.jwt-signing-key=ci_signing_key_with_32_character
app.jwt.refresh-exp-time=10
app.clients.exchange-rates.base-url=https://placeholder.ci.com
app.clients.exchange-rates.access-key=00000000000000000000000000000000
app.clients.exchange-rates.connect-timeout=3s
app.clients.exchange-rates.read-timeout=8s
app.clients.exchange-rates.caching-ttl=1m
spring.mvc.problemdetails.enabled=true
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
logging.structured.format.console=ecs
logging.structured.json.customizer=com.miguelbf.exchangerateapi.config.logging.CustomLoggingJsonMembersCustomizer
