spring.application.name=exchange-rate-api
spring.application.version=@project.version@
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json
app.jwt.access-exp-time=${APP_JWT_ACCESS_EXP_TIME}
app.jwt.jwt-signing-key=${APP_JWT_JWT_SIGNING_KEY}
app.jwt.refresh-exp-time=${APP_JWT_REFRESH_EXP_TIME}
app.clients.exchange-rates.base-url=${EXCHANGE_RATE_API_BASE_URL}
app.clients.exchange-rates.access-key=${EXCHANGE_RATE_API_ACCESS_KEY}
app.clients.exchange-rates.connect-timeout=3s
app.clients.exchange-rates.read-timeout=8s
app.clients.exchange-rates.caching-ttl=1m
spring.mvc.problemdetails.enabled=true
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
logging.structured.format.console=ecs
logging.structured.json.customizer=com.miguelbf.exchangerateapi.config.logging.CustomLoggingJsonMembersCustomizer
